package MyApp;

import MyLibs.Lot;
import MyLibs.LotDBAccess;
import java.util.List;
import javax.swing.JOptionPane;

public class LotsDisplay extends javax.swing.JFrame {

    /**
     * Creates new form LotsDisplay
     */
    public LotsDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showlots = new javax.swing.JButton();
        search = new javax.swing.JButton();
        ShowBySize = new javax.swing.JButton();
        ShowByPrice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        showlots.setText("Show Lots");
        showlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showlotsActionPerformed(evt);
            }
        });

        search.setText("Search For A Lot");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        ShowBySize.setText("Show lots by Size");
        ShowBySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBySizeActionPerformed(evt);
            }
        });

        ShowByPrice.setText("Show lots by Price");
        ShowByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowByPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showlots)
                    .addComponent(ShowBySize))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowByPrice)
                    .addComponent(search))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showlots)
                    .addComponent(search))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowBySize)
                    .addComponent(ShowByPrice))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showlotsActionPerformed
        LotDBAccess db = new LotDBAccess();
        List<Lot> allLots = db.getAllLots();
        ShowAllLots display = new ShowAllLots(allLots);
        display.setVisible(true);
    }//GEN-LAST:event_showlotsActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        SearchPrompt search = new SearchPrompt();
        search.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void ShowBySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBySizeActionPerformed
        List<Lot> sortedBySize = new LotDBAccess().getLotsSortedBySize();
        LotsBySize lbsize = new LotsBySize(this, true, sortedBySize);
        lbsize.setVisible(true);
    }//GEN-LAST:event_ShowBySizeActionPerformed

    private void ShowByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowByPriceActionPerformed
        List<Lot> sortedByPrice = new LotDBAccess().getLotsSortedByPrice();
        LotsByPrice lbprice = new LotsByPrice(this, true, sortedByPrice);
        lbprice.setVisible(true);
    }//GEN-LAST:event_ShowByPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LotsDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowByPrice;
    private javax.swing.JButton ShowBySize;
    private javax.swing.JButton search;
    private javax.swing.JButton showlots;
    // End of variables declaration//GEN-END:variables
}
