package MyApp;

import MyLibs.Lot;
import MyLibs.LotDBAccess;
import java.util.List;
import javax.swing.JOptionPane;

public class SearchPrompt extends javax.swing.JFrame {

    /**
     * Creates new form SearchPrompt
     */
    public SearchPrompt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        block = new javax.swing.JLabel();
        blockinput = new javax.swing.JTextField();
        minsize = new javax.swing.JLabel();
        minsizeInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        maxsizeInput = new javax.swing.JTextField();
        minprice = new javax.swing.JLabel();
        minpriceInput = new javax.swing.JTextField();
        maxprice = new javax.swing.JLabel();
        maxpriceInput = new javax.swing.JTextField();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        block.setText("Pick Your Desired Block Number (1-5)");

        blockinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockinputActionPerformed(evt);
            }
        });

        minsize.setText("Minimum Size Requirement");

        minsizeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minsizeInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Maximum Size Requirement");

        maxsizeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxsizeInputActionPerformed(evt);
            }
        });

        minprice.setText("Minimum Price Requirement");

        maxprice.setText("Maximum Price Requirement");

        maxpriceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxpriceInputActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(block, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blockinput)
                        .addComponent(minsize)
                        .addComponent(minsizeInput)
                        .addComponent(jLabel1)
                        .addComponent(maxsizeInput)
                        .addComponent(minprice)
                        .addComponent(minpriceInput)
                        .addComponent(maxprice)
                        .addComponent(maxpriceInput))
                    .addComponent(search))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(block)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minsize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minsizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxsizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minprice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minpriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maxprice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxpriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blockinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockinputActionPerformed

    private void minsizeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minsizeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minsizeInputActionPerformed

    private void maxsizeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxsizeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxsizeInputActionPerformed

    private void maxpriceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxpriceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxpriceInputActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
            String block = blockinput.getText();
            double minSize = Double.parseDouble(minsizeInput.getText());
            double maxSize = Double.parseDouble(maxsizeInput.getText());
            double minPrice = Double.parseDouble(minpriceInput.getText());
            double maxPrice = Double.parseDouble(maxpriceInput.getText());

            // Query DB
            List<Lot> matchingLots = LotDBAccess.searchLots(block, minSize, maxSize, minPrice, maxPrice);
            System.out.println("searchResults.size() = " + matchingLots.size());

            // Show results in a new frame
            SearchResults results = new SearchResults(matchingLots);
            results.setVisible(true);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers!");
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPrompt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel block;
    private javax.swing.JTextField blockinput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maxprice;
    private javax.swing.JTextField maxpriceInput;
    private javax.swing.JTextField maxsizeInput;
    private javax.swing.JLabel minprice;
    private javax.swing.JTextField minpriceInput;
    private javax.swing.JLabel minsize;
    private javax.swing.JTextField minsizeInput;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
